# Generated by Django 4.2.6 on 2023-11-29 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionuser',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='discussion_app.discussion'),
        ),
        migrations.AlterField(
            model_name='discussionuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='discussion_app.discussion'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
