<<<<<<< Updated upstream
# Generated by Django 4.2.6 on 2023-12-05 17:05
=======
# Generated by Django 4.2.6 on 2023-12-05 17:26
>>>>>>> Stashed changes

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
<<<<<<< Updated upstream
import django.utils.timezone
=======
>>>>>>> Stashed changes


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussion_app', '0002_alter_discussionuser_discussion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='created_by',
<<<<<<< Updated upstream
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
=======
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
>>>>>>> Stashed changes
        ),
        migrations.AlterField(
            model_name='discussion',
            name='last_message',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
