# Generated by Django 4.2.6 on 2023-12-08 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussion_app', '0002_discussion_created_by_alter_discussion_last_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='last_message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='message',
            name='post_content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='DiscussionUser',
        ),
    ]
