# Generated by Django 4.2.6 on 2023-12-08 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_app', '0003_remove_discussion_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='discussion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion_app.discussion'),
        ),
    ]
